---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biomedical-deploy
spec:
  selector:
    matchLabels:
      app: geoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: geoapp
    spec:
      containers:
      - name: biomedical-container
        image: 381492147345.dkr.ecr.us-east-1.amazonaws.com/biomedical/images:31
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: biomedical-svc
spec:
  type: LoadBalancer
  selector:
    app: geoapp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
